name: GunsAnnounce
version: '${project.version}'
api-version: 1.18
main: net.teamuni.gunsannounce.GunsAnnounce
commands:
  gunsannounce:
    permission: gunsannounce.manage
permissions:
  gunsannounce.manage:
    default: op