name: AutoAnnounce
version: '${project.version}'
api-version: 1.18
main: net.teamuni.autoannounce.AutoAnnounce
commands:
  autoannounce:
    permission: autoannounce.manage
permissions:
  autoannounce.manage:
    default: op