name: AutoAnnounce
version: '${project.version}'
api-version: 1.18
main: teamuni.net.autoannounce.AutoAnnounce
commands:
  autoannounce:
    permission: autoannounce.reload
permissions:
  autoannounce.reload:
    default: op